name: "PR - Test Updated Features"
on:
  pull_request:

jobs:
  list-filter:
    runs-on: ubuntu-latest
    outputs:
      filter: ${{ steps.set-filter.outputs.filter }}
    steps:
      - uses: actions/checkout@v3
      - id: set-filter
        run: echo "filter=$(ls ./src/ | jq -R -s -c 'split("\n")[:-1] | map( { (.|tostring):("./**/" + . + "/**") }) | add')" >> $GITHUB_OUTPUT

  list-images:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: set-matrix
        run: echo "matrix=$(jq -c '.' ./.github/baseImages.json)" >> $GITHUB_OUTPUT

  detect-changes:
    needs: [list-filter]
    runs-on: ubuntu-latest
    outputs:
      features: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: ${{ needs.list-filter.outputs.filter }}

  debug:
    needs: [list-images]
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.list-images.outputs.matrix }}
           
  test:
    needs: [detect-changes, list-images]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features:
          - gomplate
        baseImage:
          - ubuntu:focal
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test  --skip-scenarios -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

  test-scenarios:
    needs: [detect-changes]
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        features: ${{ fromJSON(needs.detect-changes.outputs.features) }}
    steps:
      - uses: actions/checkout@v3

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Testing '${{ matrix.features }}' scenarios"
        run: devcontainer features test -f ${{ matrix.features }} --skip-autogenerated  .